# Site settings
author: Antony D Sanders
title: My First CLI Project
header-img: img/home-bg.png
email: antony.devon92@gmail.com
copyright_name: Antony D Sanders
description: > # this means to ignore newlines until "baseurl:"
  Creating a Ruby Gem
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  antonysanders1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
